### PR TITLE
fix .getStyle('') and tests

### PR DESCRIPTION
**Pull request by jgchristopher**
.getStyle without a callback was failing.

### CODE REVIEW

**Comment by filmaj** [comment]
Thank you sir, about to merge in. The one thing this changes is that getStyle returns an Array now if you don't specify a callback... I think it makes sense though. I think all of the functions `get` functions need to be converted to this approach - since we are never guaranteed to be working with a single element when using xui.

**Comment by jgchristopher** [comment]
yes, you could make the other <code>get</code> methods return an Array, or you could require the use of a callback when dealing with a collection? So, <code>getStyle</code>  could throw an exception if more than one element is found.

**Comment by filmaj** [comment]
This one needs to be re-opened - the tests are not passing. See [the tests on a `querySelectorAll` compatible browser](http://xuijs.com/tests/tests/index.html) and note the `getStyle` tests passing.

**Comment by jgchristopher** [comment]
The xui-2.0.0.js doesn't look to be up to date in that test set. It is still the old code.

**Comment by filmaj** [comment]
I've re-added it and changed over the other .getXXXX functions to return Arrays.

**Pull request merged**
